spring:
  application:
    name: clima
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j
  datasource:
    url:
    username: sa
    password:
    type:
    driver-class-name:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 6
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: 8080
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
          include: "*"
