spring:
  application:
    name: clima
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j

server:
  port: 8080
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
          include: "*"
