spring:
  application:
    name: data-swim
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j
  datasource:
    url: ${SERVERLESS_DB_URL:jdbc:postgresql://localhost:5432/serveles_db}
    username: ${SERVERLESS_DB_USER:serveles_db}
    password: ${SERVERLESS_DB_PASSWORD:serveles_db}
    type:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 6
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8080
  error.whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
          include: "*"
